name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - BRANCH*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Checkout submodules
        shell: bash
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive --depth=1
      - uses: actions/setup-java@v1
        with:
          java-version: 17.0.3
          java-package: jdk+fx
      - name: Build GanttProject
        run: ./gradlew build
      - name: Publish libs
        run: ./gradlew publishToMavenLocal
      - name: Build Colloboque
        run: cd cloud.ganttproject.colloboque && ./gradlew build
